name: linux-notification-center
grade: stable
confinement: strict
base: core18
version: git
summary: Linux Notification Center
description: |
    A haskell-written notification center for users that like a desktop with style...

slots:
    dbus-daemon:
        interface: dbus
        bus: session
        name: org.freedesktop.Notifications

apps:
    linux-notification-center:
        command: $SNAP/usr/bin/deadd-notification-center
        extensions: [gnome-3-28]
        slots:
          - dbus-daemon

parts:
    linux-notification-center:
        plugin: make
        source: https://github.com/phuhl/linux_notification_center.git
        build-packages:
          - libcairo2-dev
          - libpango1.0-dev
          - libgirepository1.0-dev
          - libgtk-3-dev
          - libxml2-dev
        stage-packages:
          - curl
        build-environment:
          - PATH: "/root/.local/bin/$PATH"
        override-build: |
          mkdir -p /root/parts/linux-notification-center/install/usr/share/locale/en/LC_MESSAGES
          mkdir -p /root/parts/linux-notification-center/install/usr/share/locale/de/LC_MESSAGES
          curl -SSL https://get.haskellstack.org | sh -s - -f
          which stack
          snapcraftctl build

